### ISSUE TITLE
Use bitwise operation for intersection

### ISSUE THREAD

**Issue by RitvikPrabhu** [RitvikPrabhu/FugakuCarcinogenisis#22]

**Comment by vatai** [comment]
Hey @RitvikPrabhu,

I'll write my ideas here just in case I don't get a chance to implement them in time. I'll do it in chunks... in case I get interrupted (which is very likely).

**Comment by vatai** [comment]
One important point that it should be a "header only" implementation. Basically if you implement it in a header file it is the same as if it is in the same file.
